Repository jenkins-x/octant-jx, pull requests merged in 2020-10, with the labels that each got.

#48 fix: add 'linux' in the filename
  hack/changelog-header.md
Labels: needs-ok-to-test, size/XS

#50 fix: migrate to client-go 0.19.2 and octant 0.16
  cmd/octant-jx/main.go
  cmd/octant-jxo/main.go
  go.mod
  go.sum
  pkg/admin/router/handlers.go
  pkg/admin/views/boot_job_extra_view.go
  pkg/admin/views/boot_job_invalid_secret_view.go
  pkg/admin/views/boot_job_no_secret_view.go
  pkg/admin/views/boot_pipelines_view.go
  pkg/admin/views/failed_release_pipelines_view.go
  pkg/admin/views/health_view.go
  pkg/admin/views/health_view_test.go
  pkg/admin/views/jobs_log_view.go
  pkg/admin/views/jobs_view.go
  pkg/admin/views/overview.go
  pkg/admin/views/workspaces_view.go
  pkg/admin/workspaces/octants.go
  pkg/admin/workspaces/workspace.go
  pkg/common/helm/releases.go
  pkg/common/knative_pkg/README.md
  pkg/common/knative_pkg/duck/interface.go
  pkg/common/knative_pkg/duck/unstructured.go
  pkg/common/knative_pkg/kmeta/accessor.go
  pkg/common/knative_pkg/kmeta/owner_references.go
  pkg/common/pipelines/pipelines.go
  pkg/common/pipelines/pipelines_test.go
  pkg/common/pipelines/test_data/expected.yaml
  pkg/common/pipelines/test_data/pipelinerun.yaml
  pkg/common/pipelines/test_data/pod.yaml
  pkg/common/pluginctx/actioners/handle.go
  pkg/common/pluginctx/actioners/trigger_boot_job.go
  pkg/common/viewhelpers/cards.go
  pkg/common/viewhelpers/pipeline_helpers.go
  pkg/common/viewhelpers/resource_helpers.go
  pkg/common/viewhelpers/text.go
  pkg/plugin/views/apps_view.go
  pkg/plugin/views/environment_view.go
  pkg/plugin/views/environments_helpers.go
  pkg/plugin/views/environments_view.go
  pkg/plugin/views/helm_release_view.go
  pkg/plugin/views/helm_releases_view.go
  pkg/plugin/views/logs_view.go
  pkg/plugin/views/overview.go
  pkg/plugin/views/pipeline_container_view.go
  pkg/plugin/views/pipeline_containers_view.go
  pkg/plugin/views/pipeline_steps_render.go
  pkg/plugin/views/pipeline_terminal_view.go
  pkg/plugin/views/pipeline_view.go
  pkg/plugin/views/pipelines_render.go
  pkg/plugin/views/pipelines_view.go
  pkg/plugin/views/pipelines_view_test.go
  pkg/plugin/views/repositories_view.go
Labels: approved, size/XXL

#55 fix: avoid empty pipeline row bug
  go.mod
  go.sum
  pkg/common/pipelines/pipelines.go
  pkg/plugin/views/repositories_view.go
Labels: approved, size/L
