Repository jenkins-x/octant-jx, pull requests merged in 2020-07, with the labels that each got.

#1 docs: releases page was telling users to move the binary to the wrong…
  README.md
  jenkins-x.yml
Labels: size/M

#3 fix: create plugins directory
  Makefile
Labels: lgtm, size/S

#11 chore: enable linter
  .golangci.yml
  Makefile
  cmd/octant-jx/main.go
  cmd/octant-jxo/main.go
  go.mod
  hack/linter.sh
  jenkins-x.yml
  pkg/admin/constants.go
  pkg/admin/router/handlers.go
  pkg/admin/views/boot_job_extra_view.go
  pkg/admin/views/boot_job_no_secret_view.go
  pkg/admin/views/boot_pipelines_view.go
  pkg/admin/views/failed_release_pipelines_view.go
  pkg/admin/views/health_view.go
  pkg/admin/views/jobs_log_view.go
  pkg/admin/views/jobs_view.go
  pkg/admin/views/overview.go
  pkg/admin/views/workspaces_view.go
  pkg/admin/workspaces/octants.go
  pkg/admin/workspaces/workspace.go
  pkg/common/helm/releases.go
  pkg/common/links/common_links.go
  pkg/common/pluginctx/actioners/handle.go
  pkg/common/pluginctx/actioners/trigger_boot_job.go
  pkg/common/viewhelpers/cards.go
  pkg/common/viewhelpers/client_helpers.go
  pkg/common/viewhelpers/kube_render.go
  pkg/common/viewhelpers/links.go
  pkg/common/viewhelpers/resource_helpers.go
  pkg/common/viewhelpers/tables.go
  pkg/plugin/links.go
  pkg/plugin/util/time.go
  pkg/plugin/views/apps_view.go
  pkg/plugin/views/environment_view.go
  pkg/plugin/views/environments_view.go
  pkg/plugin/views/helm_release_view.go
  pkg/plugin/views/helm_releases_view.go
  pkg/plugin/views/logs_view.go
  pkg/plugin/views/pipeline_container_view.go
  pkg/plugin/views/pipeline_containers_view.go
  pkg/plugin/views/pipeline_steps_render.go
  pkg/plugin/views/pipeline_steps_render_test.go
  pkg/plugin/views/pipeline_terminal_view.go
  pkg/plugin/views/pipeline_view.go
  pkg/plugin/views/pipelines_render.go
  pkg/plugin/views/pipelines_view.go
  pkg/plugin/views/repositories_view.go
Labels: approved, lgtm, size/XL
