Repository jenkins-x/octant-jx, pull requests merged in 2021-01, with the labels that each got.

#148 fix: add a view of jenkins servers in the cluster
  go.mod
  go.sum
  pkg/plugin/constants.go
  pkg/plugin/router/handlers.go
  pkg/plugin/views/jenkins_view.go
Labels: approved, size/L

#191 chore(typo): fixes from Jenkin to Jenkins
  README.md
Labels: needs-ok-to-test, size/XS

#197 chore: upgrade pipelines
  .lighthouse/jenkins-x/Kptfile
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/M, updatebot
